package com.jmisur.dog.tree;

import com.jmisur.dog.mapper.YClass;
import com.jmisur.dog.mapper.YField;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class YHouse extends YClass {

    public static final YHouse house = new YHouse();

    public final YField<Integer> windowCount = new YField<Integer>("windowCount", Integer.class, this);

    public final YField<Double> squaredmeters = new YField<Double>("squaredmeters", Double.class, this);

    public final YField<String> color = new YField<String>("color", String.class, this);

    public final YField<Long> length = new YField<Long>("length", Long.class, this);

    public YHouse() {
        this("YHouse", null);
    }

    public YHouse(String name, YClass source) {
        super(name, House.class);
    }

}