package com.jmisur.dog.tree;

import com.jmisur.dog.mapper.YClass;
import com.jmisur.dog.mapper.YField;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class YTree extends YClass {

    public static final YTree tree = new YTree();

    public final YField<Integer> leafCount = new YField<Integer>("leafCount", Integer.class, this);

    public final YField<Long> height = new YField<Long>("height", Long.class, this);

    public final YField<String> color = new YField<String>("color", String.class, this);

    public final YField<Boolean> isHigh = new YField<Boolean>("isHigh", Boolean.class, this);

    public YTree() {
        this("YTree", null);
    }

    public YTree(String name, YClass source) {
        super(name, Tree.class);
    }

}