package com.jmisur.dog.car;

import com.jmisur.dog.car.Plane;
import com.jmisur.dog.generator.XClass;
import com.jmisur.dog.generator.XField;
import com.jmisur.dog.generator.XParam;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XPlane extends XClass {

    public static final Plane Plane = null;

    public static final XPlane plane = new XPlane();

    private static XParam xparam;

    public final XField engines = new XField("engines", int.class, this);

    public XPlane() {
        this("XPlane", null);
    }

    public XPlane(String name, XClass source) {
        super(name, Plane.class, source);
    }

    public XField[] getFields() {
        return new XField[] {engines};
    }

}