package com.jmisur.dog.person;

import com.jmisur.dog.generator.XClass;
import com.jmisur.dog.generator.XField;
import com.jmisur.dog.generator.XParam;
import com.jmisur.dog.person.Address;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XAddress extends XClass {

    public static final Address Address = null;

    public static final XAddress address = new XAddress();

    private static XParam xparam;

    public final XField id = new XField("id", String.class, this);

    public final XField street = new XField("street", String.class, this);

    public final XField houseNr = new XField("houseNr", Long.class, this);

    public final XField name = new XField("name", String.class, this);

    public XAddress() {
        this("XAddress", null);
    }

    public XAddress(String name, XClass source) {
        super(name, Address.class, source);
    }

    public XField[] getFields() {
        return new XField[] {id, street, houseNr, name};
    }

}