package com.jmisur.dog.person;

import com.jmisur.dog.generator.XClass;
import com.jmisur.dog.generator.XField;
import com.jmisur.dog.generator.XMethod;
import com.jmisur.dog.generator.XParam;
import com.jmisur.dog.person.Person;
import java.math.BigDecimal;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XPerson extends XClass {

    public static final Person Person = null;

    public static final XPerson person = new XPerson();

    private static XParam xparam;

    public final XField firstName = new XField("firstName", String.class, this);

    public final XField lastName = new XField("lastName", String.class, this);

    public final XAddress address = new XAddress("address", this);

    public XPerson() {
        this("XPerson", null);
    }

    public XPerson(String name, XClass source) {
        super(name, Person.class, source);
    }

    public XField[] getFields() {
        return new XField[] {firstName, lastName, address};
    }

    public XMethod getSomeStuff(Person p, BigDecimal o) {
        return new XMethod(this, "getSomeStuff", String.class, new XParam(Person.class, "p"), new XParam(BigDecimal.class, "o"));
    }

    public XMethod isAorB() {
        return new XMethod(this, "isAorB", boolean.class);
    }

    public XMethod setSomeInt(String name, Integer what) {
        return new XMethod(this, "setSomeInt", boolean.class, new XParam(String.class, "name"), new XParam(Integer.class, "what"));
    }

    public XMethod setSomeInt(String name, int what) {
        return new XMethod(this, "setSomeInt", boolean.class, new XParam(String.class, "name"), new XParam(int.class, "what"));
    }

    public XMethod setSomeObject(String name, Object what) {
        return new XMethod(this, "setSomeObject", boolean.class, new XParam(String.class, "name"), new XParam(Object.class, "what"));
    }

}