package com.jmisur.dog.person;

import java.math.BigDecimal;

import javax.annotation.Generated;

import com.jmisur.dog.generator.XClass;
import com.jmisur.dog.generator.XField;
import com.jmisur.dog.generator.XMethod;
import com.jmisur.dog.generator.XParam;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XPerson extends XClass<Person> {

	public static final Person Person = null;

	public static final XPerson person = new XPerson();

	private static XParam xparam;

	public final XField<String> firstName = new XField<String>("firstName", String.class, this);

	public final XField<String> lastName = new XField<String>("lastName", String.class, this);

	public final XAddress address = new XAddrxess("address", this);

	public XPerson() {
		this("XPerson", null);
	}

	public XPerson(String name, XClass<?> source) {
		super(name, Person.class, source);
	}

	public XField<?>[] getFields() {
		return new XField<?>[] {firstName, lastName, address};
	}

	public XMethod getSomeStuff(Person p, BigDecimal o) {
		return new XMethod("getSomeStuff", String.class, new XParam(Person.class, "p"), new XParam(BigDecimal.class, "o"));
	}

	public XMethod isAorB() {
		return new XMethod("isAorB", boolean.class);
	}

	public XMethod setSomeInt(String name, Integer what) {
		return new XMethod("setSomeInt", boolean.class, new XParam(String.class, "name"), new XParam(Integer.class, "what"));
	}

	public XMethod setSomeInt(String name, int what) {
		return new XMethod("setSomeInt", boolean.class, new XParam(String.class, "name"), new XParam(int.class, "what"));
	}

	public XMethod setSomeObject(String name, Object what) {
		return new XMethod("setSomeObject", boolean.class, new XParam(String.class, "name"), new XParam(Object.class, "what"));
	}

}