package com.jmisur.test.domain;

import com.jmisur.dto.Dto;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Dto
@Generated("Easily with JAnnocessor :)")
public class AddressXXX {

    private String id;

    private String street;

    private Long houseNr;

    private String name;

    public String getId() {
        return null;
    }

    public void setId(String id) {

    }

    public String getStreet() {
        return null;
    }

    public void setStreet(String street) {

    }

    public Long getHouseNr() {
        return null;
    }

    public void setHouseNr(Long houseNr) {

    }

    public String getName() {
        return null;
    }

    public void setName(String name) {

    }

}
