package com.jmisur.test.domain;

import com.jmisur.dto.Dto;
import com.jmisur.test.domain.Address;
import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Dto
@Generated("Easily with JAnnocessor :)")
public class PersonXXX {

    private String firstName;

    private String lastName;

    private Address address;

    public String getFirstName() {
        return null;
    }

    public void setFirstName(String firstName) {

    }

    public Address getAddress() {
        return null;
    }

    public void setAddress(Address address) {

    }

    public String getLastName() {
        return null;
    }

    public void setLastName(String lastName) {

    }

    public String getAllStuff() {
        return null;
    }

    public boolean isAorB() {
        return null;
    }

}
