package com.jmisur.test.domain;

import com.jmisur.dto.Dto;

/**
 * Generated by JAnnocessor
 */
@Dto
public class Person {

	private String firstName;

	private String lastName;

	private Address address;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAllStuff() {
		String a = "xxx";
		return "all stuff" + a;
	}

	public boolean isAorB() {
		if (Math.random() > 0) {
			return true;
		} else {
			return false;
		}
	}

	public boolean setMaNameDude(String name, int what) {
		firstName = name;
		return what > 0;
	}
}
