package com.jmisur.test.domain;

import javax.annotation.Generated;

import com.jmisur.dto.generator.XField;
import com.jmisur.dto.generator.XMethod;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XPerson extends XField<Person> {

	public static final XPerson person = new XPerson();

	public final XField<String> firstName = new XField<String>("firstName", String.class, this);

	public final XField<String> lastName = new XField<String>("lastName", String.class, this);

	public final XAddress address = new XAddress("address", this);

	public XPerson() {
		this("XPerson", null);
	}

	public XPerson(String name, XField<?> source) {
		super(name, Person.class, source);
	}

	@Override
	public XField<?>[] getFields() {
		return new XField<?>[] { firstName, lastName, address };
	}

	public XMethod getAllStuff() {
		return new XMethod("getAllStuff", String.class);
	}

	public XMethod isAorB() {
		return new XMethod("isAorB", boolean.class);
	}

	public XMethod setMaNameDude(Class<String> name, Class<Integer> what) {
		return new XMethod("setMaNameDude", boolean.class, String.class, int.class);
	}

}
