package com.jmisur.test.domain;

import com.jmisur.dog.generator.XField;
import com.jmisur.dog.generator.XMethod;
import com.jmisur.dog.generator.XParam;
import com.jmisur.test.domain.Person;

import java.math.BigDecimal;

import javax.annotation.Generated;

/**
 * Generated by JAnnocessor
 */
@Generated("Easily with JAnnocessor :)")
public class XPerson extends XField<Person> {

    public static final Person Person = null;

    public static final XPerson person = new XPerson();

    private static XParam xparam;

    public final XField<String> firstName = new XField<String>("firstName", String.class, this);

    public final XField<String> lastName = new XField<String>("lastName", String.class, this);

    public final XAddress address = new XAddress("address", this);

    public XPerson() {
        this("XPerson", null);
    }

    public XPerson(String name, XField<?> source) {
        super(name, Person.class, source);
    }

    public XField<?>[] getFields() {
        return new XField<?>[] {firstName, lastName, address};
    }

    public XMethod getSomeStuff(Person p, BigDecimal o) {
        return new XMethod("getSomeStuff", String.class, new XParam(Person.class, "p"), new XParam(BigDecimal.class, "o"));
    }

    public XMethod isAorB() {
        return new XMethod("isAorB", boolean.class);
    }

    public XMethod setMaNameDude(String name, Integer what) {
        return new XMethod("setMaNameDude", boolean.class, new XParam(String.class, "name"), new XParam(Integer.class, "what"));
    }

    public XMethod setMaNameDude(String name, Long what) {
        return new XMethod("setMaNameDude", boolean.class, new XParam(String.class, "name"), new XParam(Long.class, "what"));
    }

}
