package com.jmisur.test;

import com.jmisur.test.domain.Address;

/**
 * Generated by JAnnocessor
 */
public class PersonData15 {

    private String firstName;

    private String lastName;

    private Address address;

    private String addressName;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getAddressName() {
        return addressName;
    }

    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }

}
