package com.jmisur.test;


/**
 * Generated by JAnnocessor
 */
public class PersonData13 {

    private String lastName;

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

}
