package com.jmisur.test;

import com.jmisur.test.domain.Address;

/**
 * Generated by JAnnocessor
 */
public class PersonData31 {

    private String firstName;

    private String lastName;

    protected Address addr;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Address getAddr() {
        return addr;
    }

    public void setAddr(Address addr) {
        this.addr = addr;
    }

}
