package com.jmisur.test;

import com.jmisur.dto.Dto;

/**
 * Generated by JAnnocessor
 */
@Dto
public class Person {

	private String firstName;

	private Address address;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

}
