package com.jmisur.test;


/**
 * Generated by JAnnocessor
 */
public class PersonData12 {

    private String firstName;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

}
