package com.jmisur.test;


/**
 * Generated by JAnnocessor
 */
public class PersonData33 {

    private String firstName;

    private String lastName;

    protected AddressData30 addr;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public AddressData30 getAddr() {
        return addr;
    }

    public void setAddr(AddressData30 addr) {
        this.addr = addr;
    }

}
