package com.jmisur.test;

import com.jmisur.test.domain.Person;

/**
 * Generated by JAnnocessor
 */
public class PersonData32 {

    private String firstName;

    private String lastName;

    protected Person addr;

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Person getAddr() {
        return addr;
    }

    public void setAddr(Person addr) {
        this.addr = addr;
    }

}
