package com.jmisur.test;

import com.jmisur.test.domain.Address;

/**
 * Generated by JAnnocessor
 */
public class PersonData10 {

    private String lastName;

    private Address address;

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

}
