package com.jmisur.test;

import com.jmisur.dto.generator.XField;

/**
 * Generated by JAnnocessor
 */
public class XAddress extends XField<Address> {

    public static final XAddress address = new XAddress();

    public final XField<String> id = new XField<String>("id", String.class, this);

    public final XField<String> street = new XField<String>("street", String.class, this);

    public final XField<Long> houseNr = new XField<Long>("houseNr", Long.class, this);

    public final XField<String> name = new XField<String>("name", String.class, this);

    public XAddress() {
        this(null, null);
    }

    public XAddress(String name, XField<?> source) {
        super(name, Address.class, source);
    }

}
