package com.jmisur.test;

import com.jmisur.dto.generator.XField;

/**
 * Generated by JAnnocessor
 */
public class XPerson extends XField<Person> {

    public static final XPerson person = new XPerson();

    public final XField<String> firstName = new XField<String>("firstName", String.class, this);

    public final XAddress address = new XAddress("address", this);

    public XPerson() {
        this(null, null);
    }

    public XPerson(String name, XField<?> source) {
        super(name, Person.class, source);
    }

}
